import { fileURLToPath } from 'node:url'
import path from 'node:path'
import { readdirSync, readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import { Editor } from '@tiptap/core'
import { editorExtensions } from '../extensions'
import { markdownToJson } from '../markdown/fromMarkdown'
import { jsonToMarkdown } from '../markdown/toMarkdown'

/**
 * Same round-trip contract as roundtrip.test.ts, driven this time from the
 * Confluence importer's own output corpus (tests/fixtures/converted-markdown/,
 * regenerated by RocketWiki.Importer.Tests on every run) instead of
 * hand-written fixtures. This is the other half of design.md §13's migration
 * risk: the converter is C#, the editor is TypeScript, and nothing else
 * checks that they agree on what Markdown means. A corpus file that fails
 * here is not this suite's bug to fix — it means the converter emitted
 * Markdown the editor doesn't reproduce byte-for-byte, which is a converter
 * defect (or a genuine, currently-undocumented round-trip limitation) for
 * the importer agent to address, not something to special-case around here.
 */
function roundTrip(markdown: string): string {
  const editor = new Editor({
    extensions: editorExtensions,
    content: markdownToJson(markdown),
  })
  try {
    return jsonToMarkdown(editor.getJSON())
  } finally {
    editor.destroy()
  }
}

function corpusDirectory(): string {
  const currentDir = path.dirname(fileURLToPath(import.meta.url))
  // web/src/editor/__tests__ -> repo root is four levels up.
  return path.resolve(currentDir, '../../../../tests/fixtures/converted-markdown')
}

/**
 * The corpus is committed with LF endings (`git ls-files --eol` reports
 * i/lf), but a Windows checkout with `core.autocrlf=true` smudges the
 * working copies to CRLF. That's a checkout artifact, not corpus content —
 * this reconstructs the committed bytes so the byte-identity assertion
 * tests the canonical corpus, not the local git config. It cannot mask an
 * editor regression: only the *fixture* side is normalized; if the editor
 * ever emitted CRLF itself, `roundTrip`'s output would still mismatch.
 */
function readCorpusFile(filePath: string): string {
  return readFileSync(filePath, 'utf-8').replaceAll('\r\n', '\n')
}

// nested-unordered-list.md uses a loose list (blank line before its nested
// sub-list). That's a documented, accepted normalization — see the "loose
// lists ... tighten up" case in roundtrip.test.ts's "Known, documented
// round-trip limitations" and design.md §4's "Canonical normalization"
// table — not a converter bug, so it's asserted separately below instead of
// folded into the blanket byte-identical loop.
const DOCUMENTED_NORMALIZATIONS = new Set(['nested-unordered-list.md'])

describe('converted-markdown corpus (Confluence importer output, design.md §13)', () => {
  const dir = corpusDirectory()
  // Read the directory itself, rather than listing files by name, so new
  // corpus files the importer agent adds are picked up automatically.
  const files = readdirSync(dir).filter((name) => name.endsWith('.md'))
  const exactFiles = files.filter((name) => !DOCUMENTED_NORMALIZATIONS.has(name))

  it('the corpus directory actually has fixtures in it', () => {
    // A suite that silently iterates zero cases proves nothing while still
    // reporting green — this guards against that directory-resolution or
    // filtering ever going quietly wrong.
    expect(files.length).toBeGreaterThan(0)
  })

  it.each(exactFiles)('%s round-trips byte-identically through the editor', (fileName) => {
    const markdown = readCorpusFile(path.join(dir, fileName))
    expect(roundTrip(markdown)).toBe(markdown)
  })

  it('nested-unordered-list.md tightens up on round-trip (documented normalization, not a converter bug)', () => {
    const markdown = readCorpusFile(path.join(dir, 'nested-unordered-list.md'))
    const tightened = '- Item 1\n- Item 2\n  - Nested A\n  - Nested B\n'
    expect(roundTrip(markdown)).toBe(tightened)
  })

  it('DOCUMENTED_NORMALIZATIONS only names files that actually exist in the corpus', () => {
    // Guards against this exclusion list silently going stale (e.g. the
    // fixture gets renamed) and quietly removing coverage rather than
    // failing loudly.
    for (const name of DOCUMENTED_NORMALIZATIONS) {
      expect(files).toContain(name)
    }
  })
})
