// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RocketWiki.Data;

#nullable disable

namespace RocketWiki.Data.Migrations
{
    [DbContext(typeof(RocketWikiDbContext))]
    [Migration("20260821205534_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RocketWiki.Core.Entities.AccessRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("Action")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExpressionJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Kind")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("PageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("Role")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("SpaceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PageId");

                    b.HasIndex("SpaceId");

                    b.ToTable("AccessRules", null, t =>
                        {
                            t.HasCheckConstraint("CK_AccessRules_KindColumnPairing", "([Kind] = 1 AND [SpaceId] IS NOT NULL AND [PageId] IS NULL AND [Role] IS NOT NULL AND [Action] IS NULL) OR ([Kind] = 2 AND [PageId] IS NOT NULL AND [SpaceId] IS NULL AND [Action] IS NOT NULL AND [Role] IS NULL)");
                        });
                });

            modelBuilder.Entity("RocketWiki.Core.Entities.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("ContentHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("nvarchar(127)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("PageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .HasDatabaseName("IX_Attachments_ContentHash");

                    b.HasIndex("PageId")
                        .HasDatabaseName("IX_Attachments_PageId")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("Attachments", (string)null);
                });

            modelBuilder.Entity("RocketWiki.Core.Entities.AttributeDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AllowedValuesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("AttributeDefinitions", (string)null);
                });

            modelBuilder.Entity("RocketWiki.Core.Entities.AuditEvent", b =>
                {
                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<byte>("Channel")
                        .HasColumnType("tinyint");

                    b.Property<string>("ClientIp")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("McpClient")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte>("Outcome")
                        .HasColumnType("tinyint");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<string>("SpaceKey")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("SubjectType")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TimestampUtc", "Id");

                    b.HasIndex("Action", "TimestampUtc");

                    b.HasIndex("SubjectId", "TimestampUtc");

                    b.HasIndex("UserId", "TimestampUtc");

                    b.ToTable("AuditEvents", (string)null);
                });

            modelBuilder.Entity("RocketWiki.Core.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("EditedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("PageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("PageId", "CreatedAtUtc");

                    b.ToTable("Comments", (string)null);
                });

            modelBuilder.Entity("RocketWiki.Core.Entities.KnownGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FirstSeenAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte>("Source")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("KnownGroups", (string)null);
                });

            modelBuilder.Entity("RocketWiki.Core.Entities.Label", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SpaceId", "Name")
                        .IsUnique();

                    b.ToTable("Labels", (string)null);
                });

            modelBuilder.Entity("RocketWiki.Core.Entities.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid?>("PageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ReadAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SpaceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TitleSnapshot")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("PageId");

                    b.HasIndex("SpaceId");

                    b.HasIndex(new[] { "RecipientUserId", "CreatedAtUtc" }, "IX_Notifications_Recipient_All");

                    b.HasIndex(new[] { "RecipientUserId", "CreatedAtUtc" }, "IX_Notifications_Recipient_Unread")
                        .HasFilter("[ReadAtUtc] IS NULL");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("RocketWiki.Core.Entities.Page", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AncestorPath")
                        .IsRequired()
                        .HasMaxLength(2600)
                        .HasColumnType("nvarchar(2600)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("CurrentContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrentRevisionNumber")
                        .HasColumnType("int");

                    b.Property<Guid?>("DeleteBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ParentPageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("Id");

                    b.HasIndex("AncestorPath")
                        .HasDatabaseName("IX_Pages_AncestorPath");

                    b.HasIndex("DeleteBatchId")
                        .HasDatabaseName("IX_Pages_DeleteBatchId")
                        .HasFilter("[DeleteBatchId] IS NOT NULL");

                    b.HasIndex("ParentPageId");

                    b.HasIndex("SpaceId", "ParentPageId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Pages_Space_Parent_Slug")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("SpaceId", "ParentPageId", "SortOrder")
                        .HasDatabaseName("IX_Pages_Space_Parent_Sort");

                    b.ToTable("Pages", (string)null);
                });

            modelBuilder.Entity("RocketWiki.Core.Entities.PageEmbedding", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("ChunkHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("int");

                    b.Property<byte[]>("Embedding")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("HeadingPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("PageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("Id");

                    b.HasIndex("PageId", "ChunkIndex")
                        .IsUnique();

                    b.ToTable("PageEmbeddings", (string)null);
                });

            modelBuilder.Entity("RocketWiki.Core.Entities.PageLabel", b =>
                {
                    b.Property<Guid>("PageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LabelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PageId", "LabelId");

                    b.HasIndex("LabelId");

                    b.ToTable("PageLabels", (string)null);
                });

            modelBuilder.Entity("RocketWiki.Core.Entities.PageRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("EditSummary")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("PageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("PageId", "RevisionNumber")
                        .IsUnique();

                    b.ToTable("PageRevisions", (string)null);
                });

            modelBuilder.Entity("RocketWiki.Core.Entities.Space", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid?>("DeletedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid?>("HomepageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExported")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<long>("LastOutboxSequence")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OriginInstanceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("HomepageId");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("IX_Spaces_Key")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Spaces", (string)null);
                });

            modelBuilder.Entity("RocketWiki.Core.Entities.SyncImportState", b =>
                {
                    b.Property<string>("OriginInstanceId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("LastBundleNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastImportAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("LastManifestHash")
                        .IsRequired()
                        .HasColumnType("char(64)");

                    b.HasKey("OriginInstanceId");

                    b.ToTable("SyncImportStates", (string)null);
                });

            modelBuilder.Entity("RocketWiki.Core.Entities.SyncOutboxEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<byte>("EventType")
                        .HasColumnType("tinyint");

                    b.Property<int?>("ExportedInBundle")
                        .HasColumnType("int");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SpaceId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("SyncOutboxEvents", (string)null);
                });

            modelBuilder.Entity("RocketWiki.Core.Entities.SyncSpaceState", b =>
                {
                    b.Property<string>("OriginInstanceId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("AppliedSequence")
                        .HasColumnType("bigint");

                    b.HasKey("OriginInstanceId", "SpaceId");

                    b.ToTable("SyncSpaceStates", (string)null);
                });

            modelBuilder.Entity("RocketWiki.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttributesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Subject")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("Subject")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Subject")
                        .HasFilter("[Subject] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("RocketWiki.Core.Entities.Watch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid?>("PageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SpaceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PageId");

                    b.HasIndex("SpaceId");

                    b.HasIndex(new[] { "UserId", "PageId" }, "IX_Watches_User_Page")
                        .IsUnique()
                        .HasFilter("[PageId] IS NOT NULL");

                    b.HasIndex(new[] { "UserId", "SpaceId" }, "IX_Watches_User_Space")
                        .IsUnique()
                        .HasFilter("[SpaceId] IS NOT NULL");

                    b.ToTable("Watches", null, t =>
                        {
                            t.HasCheckConstraint("CK_Watches_SpaceXorPage", "([SpaceId] IS NOT NULL AND [PageId] IS NULL) OR ([SpaceId] IS NULL AND [PageId] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("RocketWiki.Core.Entities.AccessRule", b =>
                {
                    b.HasOne("RocketWiki.Core.Entities.Page", "Page")
                        .WithMany("Restrictions")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("RocketWiki.Core.Entities.Space", "Space")
                        .WithMany("AccessRules")
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Page");

                    b.Navigation("Space");
                });

            modelBuilder.Entity("RocketWiki.Core.Entities.Attachment", b =>
                {
                    b.HasOne("RocketWiki.Core.Entities.Page", "Page")
                        .WithMany("Attachments")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RocketWiki.Core.Entities.User", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Page");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("RocketWiki.Core.Entities.AuditEvent", b =>
                {
                    b.HasOne("RocketWiki.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");
                });

            modelBuilder.Entity("RocketWiki.Core.Entities.Comment", b =>
                {
                    b.HasOne("RocketWiki.Core.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RocketWiki.Core.Entities.Page", "Page")
                        .WithMany("Comments")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RocketWiki.Core.Entities.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Author");

                    b.Navigation("Page");

                    b.Navigation("ParentComment");
                });

            modelBuilder.Entity("RocketWiki.Core.Entities.Label", b =>
                {
                    b.HasOne("RocketWiki.Core.Entities.Space", "Space")
                        .WithMany("Labels")
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Space");
                });

            modelBuilder.Entity("RocketWiki.Core.Entities.Notification", b =>
                {
                    b.HasOne("RocketWiki.Core.Entities.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("RocketWiki.Core.Entities.Page", "Page")
                        .WithMany()
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("RocketWiki.Core.Entities.User", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RocketWiki.Core.Entities.Space", "Space")
                        .WithMany()
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Actor");

                    b.Navigation("Page");

                    b.Navigation("Recipient");

                    b.Navigation("Space");
                });

            modelBuilder.Entity("RocketWiki.Core.Entities.Page", b =>
                {
                    b.HasOne("RocketWiki.Core.Entities.Page", "ParentPage")
                        .WithMany("ChildPages")
                        .HasForeignKey("ParentPageId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("RocketWiki.Core.Entities.Space", "Space")
                        .WithMany("Pages")
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ParentPage");

                    b.Navigation("Space");
                });

            modelBuilder.Entity("RocketWiki.Core.Entities.PageEmbedding", b =>
                {
                    b.HasOne("RocketWiki.Core.Entities.Page", "Page")
                        .WithMany()
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("RocketWiki.Core.Entities.PageLabel", b =>
                {
                    b.HasOne("RocketWiki.Core.Entities.Label", "Label")
                        .WithMany("PageLabels")
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RocketWiki.Core.Entities.Page", "Page")
                        .WithMany("PageLabels")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Label");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("RocketWiki.Core.Entities.PageRevision", b =>
                {
                    b.HasOne("RocketWiki.Core.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RocketWiki.Core.Entities.Page", "Page")
                        .WithMany("Revisions")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("RocketWiki.Core.Entities.Space", b =>
                {
                    b.HasOne("RocketWiki.Core.Entities.Page", "Homepage")
                        .WithMany()
                        .HasForeignKey("HomepageId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Homepage");
                });

            modelBuilder.Entity("RocketWiki.Core.Entities.SyncOutboxEvent", b =>
                {
                    b.HasOne("RocketWiki.Core.Entities.Space", "Space")
                        .WithMany()
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Space");
                });

            modelBuilder.Entity("RocketWiki.Core.Entities.Watch", b =>
                {
                    b.HasOne("RocketWiki.Core.Entities.Page", "Page")
                        .WithMany()
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("RocketWiki.Core.Entities.Space", "Space")
                        .WithMany()
                        .HasForeignKey("SpaceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("RocketWiki.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Page");

                    b.Navigation("Space");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RocketWiki.Core.Entities.Comment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("RocketWiki.Core.Entities.Label", b =>
                {
                    b.Navigation("PageLabels");
                });

            modelBuilder.Entity("RocketWiki.Core.Entities.Page", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("ChildPages");

                    b.Navigation("Comments");

                    b.Navigation("PageLabels");

                    b.Navigation("Restrictions");

                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("RocketWiki.Core.Entities.Space", b =>
                {
                    b.Navigation("AccessRules");

                    b.Navigation("Labels");

                    b.Navigation("Pages");
                });
#pragma warning restore 612, 618
        }
    }
}
