using Microsoft.EntityFrameworkCore;
using RocketWiki.Core.Entities;
using RocketWiki.Core.Enums;
using Xunit;

namespace RocketWiki.Data.Tests;

/// <summary>
/// AuditEvent has a composite clustered PK (TimestampUtc, Id) per data-model.md, with Id
/// still meant to be a store-generated bigint identity even though it isn't the sole key
/// column. Proving this against SQLite surfaced a genuine gap, since fixed: SQLite's
/// rowid-alias autoincrement mechanism only applies when an INTEGER column is the SOLE
/// primary key, so leaving Id unset used to fail with a NOT NULL violation here. SQL
/// Server does not share this limitation - IDENTITY is a column-level property there,
/// independent of key structure, confirmed by the generated migration still marking Id
/// with `.Annotation("SqlServer:Identity", "1, 1")` despite being part of the composite
/// PK - so production code can always leave Id unset and let the database generate it.
/// <see cref="RocketWiki.Data.SqliteAuditEventIdGenerator"/> closes the gap for SQLite
/// specifically (wired up in RocketWikiDbContext.OnModelCreating), so both providers now
/// support the same "leave Id unset" calling convention; the first test below exercises
/// that generation path directly, and the rest use explicit Ids only to make the
/// composite-key assertions unambiguous to read.
/// </summary>
public class AuditEventCompositeKeyTests : SqliteTestBase
{
    [Fact]
    public void UnsetId_IsAutoGeneratedOnSqlite_ViaSqliteAuditEventIdGenerator()
    {
        using var context = CreateContext();
        context.AuditEvents.Add(new AuditEvent
        {
            // Id deliberately left at its CLR default (0), exactly how production code
            // on SQL Server would leave it for IDENTITY to fill in.
            TimestampUtc = DateTime.UtcNow,
            Action = "page.view",
            Outcome = AuditOutcome.Success,
            Channel = AuditChannel.GraphQl,
            RequestId = "req-1",
            ClientIp = "127.0.0.1",
        });

        context.SaveChanges();

        var saved = context.AuditEvents.Local.Single();
        Assert.True(saved.Id > 0);
    }

    [Fact]
    public void MultipleEvents_DistinctTimestamps_WithExplicitIds_PersistCorrectly()
    {
        using var context = CreateContext();
        var events = new[]
        {
            NewEvent(1, DateTime.UtcNow),
            NewEvent(2, DateTime.UtcNow.AddSeconds(1)),
            NewEvent(3, DateTime.UtcNow.AddSeconds(2)),
        };
        context.AuditEvents.AddRange(events);
        context.SaveChanges();

        using var readContext = CreateContext();
        Assert.Equal(3, readContext.AuditEvents.Count());
    }

    [Fact]
    public void MultipleEvents_SameTimestamp_DifferentIds_CompositeKeyAllowsBoth()
    {
        var sameTimestamp = DateTime.UtcNow;

        using var context = CreateContext();
        context.AuditEvents.AddRange(NewEvent(1, sameTimestamp), NewEvent(2, sameTimestamp));
        context.SaveChanges();

        using var readContext = CreateContext();
        Assert.Equal(2, readContext.AuditEvents.Count(e => e.TimestampUtc == sameTimestamp));
    }

    [Fact]
    public void DuplicateCompositeKey_SameTimestampAndId_IsRejected()
    {
        var sameTimestamp = DateTime.UtcNow;

        using (var writeContext = CreateContext())
        {
            writeContext.AuditEvents.Add(NewEvent(1, sameTimestamp));
            writeContext.SaveChanges();
        }

        // A fresh context for the duplicate insert: reusing the first context would hit
        // EF's own client-side identity-map conflict check (InvalidOperationException)
        // before any SQL is sent, proving EF's in-memory tracking works rather than
        // proving the database's own PRIMARY KEY constraint rejects the duplicate.
        using var duplicateContext = CreateContext();
        duplicateContext.AuditEvents.Add(NewEvent(1, sameTimestamp));

        Assert.ThrowsAny<DbUpdateException>(() => duplicateContext.SaveChanges());
    }

    [Fact]
    public void Event_PersistsAndReloads_WithAllFieldsIntact()
    {
        var timestamp = DateTime.UtcNow;
        var subjectId = Guid.NewGuid();

        using (var writeContext = CreateContext())
        {
            writeContext.AuditEvents.Add(new AuditEvent
            {
                Id = 100,
                TimestampUtc = timestamp,
                UserId = null, // system actor
                Action = "sync.import",
                SubjectType = AuditSubjectType.Space,
                SubjectId = subjectId,
                SpaceKey = "ENG",
                Outcome = AuditOutcome.Success,
                Channel = AuditChannel.Sync,
                RequestId = "req-1",
                ClientIp = "127.0.0.1",
                McpClient = null,
                DetailsJson = """{"bundle":41}""",
            });
            writeContext.SaveChanges();
        }

        using var readContext = CreateContext();
        var reloaded = readContext.AuditEvents.Single(e => e.SubjectId == subjectId);

        Assert.Null(reloaded.UserId);
        Assert.Equal("sync.import", reloaded.Action);
        Assert.Equal(AuditOutcome.Success, reloaded.Outcome);
        Assert.Equal(AuditChannel.Sync, reloaded.Channel);
        Assert.Equal("ENG", reloaded.SpaceKey);
    }

    private static AuditEvent NewEvent(long id, DateTime timestamp) => new()
    {
        Id = id,
        TimestampUtc = timestamp,
        Action = "page.view",
        Outcome = AuditOutcome.Success,
        Channel = AuditChannel.GraphQl,
        RequestId = Guid.NewGuid().ToString("N"),
        ClientIp = "127.0.0.1",
    };
}
