mutation AddComment($input: AddCommentInput!) {
  addComment(input: $input) {
    comment {
      id
      parentCommentId
      body
      isDeleted
      authorDisplayName
      createdAtUtc
      editedAtUtc
    }
    readOnlyReplicaError {
      message
      originInstanceId
    }
  }
}

mutation DeleteComment($input: DeleteCommentInput!) {
  deleteComment(input: $input) {
    comment {
      id
      isDeleted
      body
    }
    readOnlyReplicaError {
      message
      originInstanceId
    }
  }
}
